### ISSUE TITLE
pip, not conda?

### ISSUE THREAD

**Issue by smythp** [GCDigitalFellows/installdri.github.io#16]
Conda didn't work during the session last time, but pip seemed to work fine. Would recommend pip for the tweepy part. Don't test in anaconda, test in terminal.

**Comment by story645** [comment]
did you use the full command?
`conda install -c conda-forge tweepy -y`

 The conda forge bit is really important, as yes conda doesn't package tweepy, but conda-forge does. https://github.com/conda-forge/tweepy-feedstock

**Comment by smythp** [comment]
Nope, that was probably it.
