### ISSUE TITLE
Make stubs for linking

### ISSUE THREAD

**Issue by smythp** [GCDigitalFellows/installdri.github.io#17]
Can you get this to the point where we have stable files for linking? Want to start adding installation links to the various repos in the next few days. Remember that they should be in a sections folder or similar so there isn't a mess of files in the top-level directory.

**Comment by story645** [comment]
Can we do this in reverse? As you're adding links, throw a blank file into sections for the stub. That way, I know what software needs to be installed. I'll port content if it exists and create it if it doesn't.  (Plus, I don't think I can get to it before Sunday).
