### ISSUE TITLE
Jekyll

### ISSUE THREAD

**Issue by story645** [GCDigitalFellows/installdri.github.io#22]
for website install joy fun

**Comment by smythp** [comment]
Link to instructions for reference: https://github.com/smythp/jekyll/blob/master/installation.md

**Comment by story645** [comment]
https://jekyllrb.com/docs/windows/

**Comment by story645** [comment]
possibly use anaconda jekyll on windows

**Comment by story645** [comment]
tentative solution to this is to use instructions from https://github.com/GCDigitalFellows/dhri-website
